### ISSUE TITLE
Unknow format date

### ISSUE THREAD

**Issue by carminepat** [inkblotty/pk-date-helpers#7]
I have this date, and I don't know format. First part, before ":" are five digits date. Second part, I imagine, is hour, minute second, but I don't know how to parse it. Can you help me, please? CREATION_DATE=42433:6382323727

**Comment by inkblotty** [comment]
Hi @carminepat —

This package doesn’t look like the solution you’re looking for, but if your suspicions are correct, you could use DateTime from Luxon to parse the first and second parts of your date.

pk-date-helpers only supports the formats listed in the README.

**Comment by carminepat** [comment]
Thank you, for response. If you have idea of second part format, share with me solution, thank you
